config/routes.rb
Rails.application.routes.draw do

  resources :contents
  devise_for :users
  # root: comando solo per la pagina iniziale
  root 'pages#home'

  #   get 'about' => 'pages#about'
  # Spiegazione: una volta clicato il link about deve far partire il controller pages#about
  get 'about' => 'pages#about'


  post '/compra/:slug', to: 'transaction#create', as: :compra
  get '/pickup/:guid', to: 'transaction#pickup', as: :pickup

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  extend FriendlyId
  friendly_id :titolo, use: :slugged




  belongs_to :user

  has_many :sales

  has_attached_file :cover
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/,
  message: "Solo le immagini sono supportate"


  has_attached_file :allegato
    validates_attachment_content_type :allegato, :content_type => [ /^image\/(png|gif|jpeg)/,'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/pdf', 'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','audio/mpeg', 'audio/mp3' ],
    message: "Formato non supportato"

    validates :titolo, :descrizione, :price, presence: true

    # greater_than: 49 perche il metodo di pa gamento Stripe accetta minimo 50 centesimi
    validates :price, numericality: { greater_than: 0.49 }

    validates :cover, attachment_presence: true
    validates :allegato, attachment_presence: true


end

app/models/sale.rb
class Sale < ApplicationRecord
  # Chiama la funzione generate_guid prima della crazione del Content
  before_create :generate_guid

  belongs_to :content

  include AASM

  aasm column: 'state' do

    state :sleeping, :initial => true
    state :running
    state :completed
    state :errored

    event :running, after: :charge_card do
      transitions from: :sleeping, to: :running
    end

    event :complete do
      transitions from: :running, to: :completed
    end

    event :fails do
      transitions from: :running, to: :errored
    end


  end

  def charge_card
    begin
        save!
        charge = Stripe::Charge.create(
          amount: self.amount,
          currency: "eur",
          card: self.stripe_token,
          description: "vendita di un contenuto"
          )
        self.update(stripe_id: charge.id)
        self.complete!
    rescue Stripe::StripeError => e
      self.update_attributes(error: e.message)
      self.fail!

    end
  end

  private

    def generate_guid
      # Fuzione che genere un guid randomico sicuro (guid = una specie di ID(non Integer ma string)
      # per le transazioni piu sicuro)
        self.guid = SecureRandom.uuid()
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :contents

# validazione per nome, emil e pass gia di default di device
 validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])

  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]


  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)

  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = current_user.contents.build
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'il contenuto è stato creato con successo.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Il contenuto è stato aggiornato con successo.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Il contenuto è stato eliminato.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.friendly.find(params[:id])


    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price, :cover, :allegato)
    end

    def check_user
      if current_user != @content.user
        redirect_to root_url, alert: "Non  hai accesso a questa pagina"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end


  def about

  end

end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController

    def create
      content = Content.find_by!(slug: params[:slug])
      sale = content.sales.create(
        amount: (content.price * 100).floor,
        email_acquirente: current_user.email,
        email_venditore: content.user.email,
        stripe_token: params[:stripeToken]
      )
      sale.running!

      if sale.completed?
        redirect_to pickup_url(guid: sale.guid)
      else
        redirect_to content_path(content), notice: @error
      end

    end

    def pickup
      @sale = Sale.find_by!(guid: params[:guid])
      @content = @sale.content
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true,html: { multipart: true }) do |form| %>
<% if content.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(content.errors.count, "error") %>
      prohibited this content from being saved:</h2>

    <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="field">
  <label class="grey-text">Carica il contenuto digitale che vuoi vendere(formati supportati PowerPoint, Excel, Word, PDF, Immagini e MP3)</label>
  <br>
  <%= form.file_field :allegato %>
</div>
<div class="field">
  <%= form.label :titolo %>
  <%= form.text_field :titolo, id: :content_titolo %>
</div>

<div class="field">
  <%= form.label :descrizione %>
  <%= form.text_area :descrizione, id: :content_descrizione, class: "materialize-textarea" %>
</div>

<div class="field">
  <%= form.label :Prezzo_min_50_cent %>
  <%= form.text_field :price, id: :content_price %>
</div>

<div class="field">
  <label class="grey-text">Carica un immagine da utilizzare come anteprima del tuo contenuto</label>
  <br>
  <%= form.file_field :cover %>
</div>
<br>
<div class="actions">
  <%= form.submit 'Salva contenuto', class: "btn btn-form" %>
</div>
<br>
<% end %>

app/views/contents/edit.html.erb
<h1 class="center">Modfica contenuto <%= @content.titolo %></h1>

<%= render 'form', content: @content %>

<%= link_to 'Mostra contenuto', @content %> |
<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/index.html.erb
<!-- <h1>Contents</h1> -->

<div class="row">
  <% @contents.each do |content| %>

    <div class="col s12 m4 l3">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag content.cover.url(), class: "activator" %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= content.titolo %>
            <i class="material-icons right">more_vert</i>
          </span>
          <div>
            <span>Venduto da:
              <%= content.user.name %></span>
            <span class="right"><%= number_to_currency(content.price) %></span>
          </div>
          <br>
          <div class="center"><%= link_to 'Scopri di piu', content, class: "btn" %></div>
          <% if content.user == current_user %>
          <br>
            <div class="center">
              <p><%= link_to 'Modifica', edit_content_path(content) %>
                <%= link_to 'Elimina', content, method: :delete, data: { confirm: 'Sei sicur di cancellare?' } %>
              </p>
            </div>
          <% end %>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i>
          </span>
          <p><%= content.descrizione %></p>
        </div>
      </div>
    </div>
  <% end %>

</div>

<br>
<div class="center">
<%= will_paginate @contents, renderer: MaterializePagination::Rails %>
</div>

app/views/contents/new.html.erb
<h1 class="center">Aggiungi un contenuto digitale</h1>

<%= render 'form', content: @content %>

<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/show.html.erb
<div class="row">
  <div class="col l6">
    <%= image_tag @content.cover.url(), class:  "responsive-img show-img" %>

  </div>
  <div class="col l6">
    <h3 class="show-titolo">
      <strong>Titolo:</strong>
      <%= @content.titolo %>
    </h3>
    <h4 class="show-price">
      <strong>Price:</strong>
      <%= number_to_currency(@content.price) %>
    </h4>
    <p>Venduto da: <%= @content.user.name %></p>
    <p>
      <strong>Descrizione:</strong>
      <%= @content.descrizione %>
    </p>
    <% if current_user%>

    <%= form_tag compra_path(slug: @content.slug) do %>
      <script
        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-amount="<%= (@content.price * 100).floor %>"
        data-name=" Marketplace "
        data-description=" <%= @content.titolo %> "
        data-email="<%= current_user.email %>"
        data-locale="auto"
        data-currency="eur">
      </script>
    <% end %>
    <% else %>
        <p>Fai <%= link_to "Login", new_user_session_path %> o <%= link_to "Registrati", new_user_registration_path %> per acquistare</p>
        <% end %>
  </div>
</div>


<% if @content.user == current_user %>

  <%= link_to 'Edit', edit_content_path(@content) %>
  |
<% end %>
<%= link_to 'Torna ai contenuti', contents_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer grey darken-2 center">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col s4">© 2018 Copyright Riccardo</div>
        <div class="col s4">
          <a href="http://www.google.it" target="_blank">
            <i class="fa-social fa fa-facebook fa-2x white-text" aria-hidden="true"></i>
          </a>
          <a href="http://www.google.it" target="_blank">
            <i class="fa-social fa fa-twitter fa-2x white-text" aria-hidden="true"></i>
          </a>
        </div>
        <div class="col s4">
          <%= link_to "About", about_path, class: "grey-text text-lighten-4 right" %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
  <nav class="grey darken-3">
    <div class="nav-wrapper container ">

      <%= link_to '<i class="fa fa-floppy-o"> Marketplace</i>'.html_safe, root_path, class: "brand-logo" %>

      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">

        <%= link_to 'Vendi Contenuto', new_content_path %>


        <% if user_signed_in? %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
        <% else %>
            <li><%= link_to "Login", new_user_session_path  %></li>
            <li><%= link_to "Registrati", new_user_registration_path  %></li>
        <% end %>


      </ul>
      <ul class="side-nav" id="mobile-demo">
        <% if user_signed_in? %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
        <% else %>
            <li><%= link_to "Login", new_user_session_path  %></li>
            <li><%= link_to "Registrati", new_user_registration_path  %></li>
            <li><%= link_to 'Vendi Contenuto', new_content_path %></li>
        <% end %>

      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,600" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <!-- Header, Footer -->
  <body>

    <!-- Carica il parziale _header -->
    <%= render "layouts/header" %>

    <div class="container">
      <% flash.each do |type, message|%>
      <script>
        Materialize.toast('<%= message %>', 4000)
      </script>
      <% end %>
    </div>

    <%= render 'pages/slider' if action_name == 'home'%>

    <main class="container">
      <!-- yield -> carica le pages home e about --->
      <%= yield %>
    </main>
    <%= render "layouts/footer"%>

  </body>
  <script type="text/javascript">
    $(".button-collapse").sideNav();
  </script>
</html>

app/views/pages/_slider.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <br><br>
    <div class="row center">
      <h1>Marketplace</h1>

      <h5>Vendi e acquista contenuti digitli</h5>
    </div>
    <div class="row center">
      <%= link_to "Vai ai contenuti",contents_path, class: "btn red btn-large" %>
    </div>
    <br><br>
  </div>
  <div class="materialboxed parallax "><%= image_tag("home.jpg") %></div>
</div>

app/views/pages/about.html.erb
<h1>Chi siamo</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/pages/home.html.erb
<div class="center">

  <!-- Icon Section -->
  <div class="row">
    <h2 class="home-subtitles">Il negozio online di contenuti digitali</h2>

    <div class="col s12 m4">
      <i class="material-icons medium blue-grey-text text-darken-3">library_books</i>
      <h5>Scopri contenuti unici</h5>

      <p>Scegli tra formati disponibili il documento che stai cercando</p>
    </div>

    <div class="col s12 m4">
      <i class="material-icons medium blue-grey-text text-darken-3">motorcycle</i>
      <h5>Acquista velocemente</h5>
      <p>Scegli il prodotto che ti interessa in pochi secondi potrei iniziare ad utilizzarlo</p>
    </div>

    <div class="col s12 m4">
      <i class="material-icons medium blue-grey-text text-darken-3">library_add</i>
      <h5>Vendi i tuoi contenuti</h5>
      <p>Hai documenti che vorresti vendere aggiungili alla libreria ed inizia a guadagnare</p>
    </div>
  </div>
</div>

app/views/transaction/pickup.html.erb
<h1>Grazie per l acquisto</h1>

<p>Scarica qui il tuo contenuto <%= link_to "LINK", @content.allegato.url %></p></p>